services:
  Simply\Core\Cache\CacheFactory:
    arguments: [ '%cache_configurations%' ]

  Simply\Core\Contract\CacheInterface:
    factory: ['@Simply\Core\Cache\CacheFactory', 'createCacheObject']
    lazy: true

  framework.cache:
    alias: Simply\Core\Contract\CacheInterface
    public: true
