services:
  framework.manager:
    class: SimplyFramework\Manager\FrameworkChainedManager
    public: true
    arguments:
      - !tagged_iterator framework_manager

  framework.manager.metabox:
    class: SimplyFramework\Manager\MetaboxManager
    arguments: ['%metaboxes%', '@framework.form_generator']
    tags: ['framework_manager']

  framework.manager.command:
    class: SimplyFramework\Manager\CommandManager
    arguments:
      - !tagged_iterator wpcli_command
    tags: ['framework_manager']

  framework.manager.post_type:
    class: SimplyFramework\Manager\PostTypeManager
    arguments: ['%post_type%']
    tags: ['framework_manager']
