services:
  framework.template_engine:
    class: Simply\Core\Template\TemplateEngine
    public: true
    lazy: true
  Simply\Core\Template\TemplateEngine:
    public: true
    autowire: true
    lazy: true
