services:
  Simply\Core\Command\ClearCacheCommand:
    tags: ['wpcli_command']

  Simply\Core\Command\CreateDefaultPluginCommand:
    tags: ['wpcli_command']

  Simply\Core\Command\CreateDefaultThemeCommand:
    tags: [ 'wpcli_command' ]
