services:
  SimplyFramework\Command\ClearCacheCommand:
    tags: ['wpcli_command']

  SimplyFramework\Command\CreateDefaultPluginCommand:
    tags: ['wpcli_command']

  SimplyFramework\Command\CreateDefaultThemeCommand:
    tags: [ 'wpcli_command' ]
